# Generated by Django 4.1.7 on 2023-06-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwidder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='static/media/blank-profile-picture.png', upload_to='static/media/'),
        ),
    ]
