# Generated by Django 4.1.7 on 2023-06-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwidder', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='static/media/blank-profile-picture.png', upload_to='media/profile_images/'),
        ),
    ]
